# Assignment 4

Ques 1 :

Write a program to create a NumPy 1D-array with 5 elements and perform basic operations like:

a) Addition of 2 in all the element

b) Multiply 3 with all the elements

c) Divide every element by 2

In [10]:
import numpy as np
myarr=np.array([56,42,24,48,50])
print(f"Array elements : {myarr}")
# 1(a)
myaddarr=myarr+2
print(f"Array after adding 2 to each element : {myaddarr}")
# 1(b)
mymularr=myarr*3
print(f"Array after multiplying 3 to each element : {mymularr}")
# 1(c)
mydivarr=myarr//2
print(f"Array after dividing each element by 2 : {mydivarr}")


Array elements : [56 42 24 48 50]
Array after adding 2 to each element : [58 44 26 50 52]
Array after multiplying 3 to each element : [168 126  72 144 150]
Array after dividing each element by 2 : [28 21 12 24 25]


Ques 2 :

Questions on Basic NumPy Array:

a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

b) Find the most frequent value and their indice(s) in the following arrays:

i. x = np.array([1,2,3,4,5,1,2,1,1,1])

ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [44]:
import numpy as np
arr=np.array([1,2,3,6,4,5])
print(f"Original array : {arr}")
# 2(a)
revarr=np.flip(arr)
print(f"reversed array : {revarr}")

# 2(b)-(i)
x=np.array([1,2,3,4,5,1,2,1,1,1,8])
most_freq_x=np.bincount(x).argmax()
most_freq_x_idxs=np.where(x==most_freq_x)[0]
print(most_freq_x)
print(most_freq_x_idxs)

# 2(b)-(ii)
y=np.array([1,1,1,2,3,4,2,4,3,3,3])
most_freq_y=np.bincount(y).argmax()
most_freq_y_idxs=np.where(y==most_freq_y)[0]
print(most_freq_y)
print(most_freq_y_idxs)
print(type(most_freq_y_idxs))


Original array : [1 2 3 6 4 5]
reversed array : [5 4 6 3 2 1]
1
[0 5 7 8 9]
3
[ 4  8  9 10]
<class 'numpy.ndarray'>


Ques 3 :

For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access
elements using row and column indices as follows:

a) Access 1st row, 2nd column

b) Access 3rd row, 1st column

In [37]:
import numpy as np
arr=np.array([[10,20,30],
              [40,50,60],
              [70,80,90]])
print(arr[0,1])
print(arr[2,0])

20
70


Ques 4 :

Write program to create an 1-D NumPy array named <<your name>> with evenly
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array,
shape, total elements, the data type of each element and total number of bytes consumed
by the array. Find the transpose of this array using reshape() attribute. Can we do the same
with T attribute?

In [85]:
import numpy as np
neeraj=np.array(np.linspace(10,100,25))
print(f"25 numbers btw 10 and 100 equally spaced : \n{neeraj}")
print(f"shape : {neeraj.shape}")
print(f"total elements : {neeraj.size}")
print(f"data type of elements : {neeraj.dtype}")
print(f"Total number of bytes consumed : {neeraj.nbytes}")
transpose_neeraj=np.reshape(neeraj,(25,1))
print(f" Transpose of neeraj : \n{transpose_neeraj}")
print(f" Transpose of transpose_neeraj : \n{transpose_neeraj.T}")

25 numbers btw 10 and 100 equally spaced : 
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
shape : (25,)
total elements : 25
data type of elements : float64
Total number of bytes consumed : 200
 Transpose of neeraj : 
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
 Transpose of transpose_neeraj : 
[[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
   47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
   85.    88.75  92.5   96.25 100.  ]]


Ques 5 :

Create a 2-D Array of three rows and four columns, named ucs420_<your_name>>
with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean,
median, max, min, unique elements. Reshape the array to four rows and three columns and
name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three
columns and name it as resized_ ucs420_<your_name>>.

In [88]:
import numpy as np
ucs420_neeraj=np.array([[10,20,30,40],[50,60,70,80],[90,15,20,35]])
print(f"Original array : \n{ucs420_neeraj}")
maxxx=np.max(ucs420_neeraj)
print(f"max element : {maxxx}")
minnn=np.min(ucs420_neeraj)
print(f"min element : {minnn}")
mean_ucs420_neeraj=np.mean(ucs420_neeraj)
print(f"mean of elements : {mean_ucs420_neeraj}")
median_ucs420_neeraj=np.median(ucs420_neeraj)
print(f"median of elements : {median_ucs420_neeraj}")
uniq_ucs420_neeraj=np.unique(ucs420_neeraj)
print(f"unique elements : {uniq_ucs420_neeraj}")
reshaped_ucs420_neeraj=np.reshape(ucs420_neeraj,(4,3))
print(f"reshaped : \n{reshaped_ucs420_neeraj}")
resize_ucs420_neeraj=np.resize(ucs420_neeraj,(2,3))
print(f"resized : \n{resize_ucs420_neeraj}")

Original array : 
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
max element : 90
min element : 10
mean of elements : 43.333333333333336
median of elements : 37.5
unique elements : [10 15 20 30 35 40 50 60 70 80 90]
reshaped : 
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
resized : 
[[10 20 30]
 [40 50 60]]
